#!/bin/bash

echo "🚀 FE1 Jira 통합 관리 터널 시작 가이드"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Next.js 서버가 3000 포트에서 실행 중인지 확인됨"
echo ""
echo "📝 다음 단계를 따라주세요:"
echo ""
echo "1️⃣  VPN 연결 해제 (잠깐만!)"
echo "   → VPN 클라이언트에서 연결 끊기"
echo ""
echo "2️⃣  아래 명령어 실행:"
echo "   → ngrok http 3000"
echo ""
echo "3️⃣  생성된 URL 복사 (예: https://abc-123-def.ngrok-free.app)"
echo ""
echo "4️⃣  VPN 다시 연결"
echo "   → 터널은 계속 유지됩니다!"
echo ""
echo "5️⃣  팀원들에게 URL 공유"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  주의사항:"
echo "   - ngrok 무료 버전은 세션마다 URL이 바뀝니다"
echo "   - 고정 URL이 필요하면 ngrok 유료($8/월) 고려"
echo "   - 터널이 끊기면 위 과정을 다시 실행"
echo ""
echo "💡 팁: 터널 실행 후 http://localhost:4040 에서 모니터링 가능"

